name: Build and Deploy
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Deploy artifact gecko-form-generator
        uses: actions/upload-artifact@v2
        with:
          name: gecko-form-generator
          path: dist/bundles/gecko-form-generator.js
          public: true
      - name: Deploy artifact gecko-form-generator-haefeli
        uses: actions/upload-artifact@v2
        with:
          name: gecko-form-generator-haefeli
          path: dist/bundles/gecko-form-generator-haefeli.js
          public: true
